server:
  port: 18060
spring:
  datasource:
    url: jdbc:mysql://192.168.1.48:3306/demo?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123
mybatis:
  type-aliases-package: com.alex.ni.mybatis
  mapper-locations: classpath:mapper/*Mapper.xml