server:
  port: 8060
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
mybatis:
  type-aliases-package: com.alex.ni.mybatis
  mapper-locations: classpath:mapper/*Mapper.xml